apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  annotations:
    kubernetes.io/change-cause: "Metadata service deployment"
  labels:
    app: metadata-service
spec:
  # modify replicas according to your case
  strategy:
    type: RollingUpdate
    # type: Recreate
  replicas: 3
  selector:
    matchLabels:
      tier: metadata-service
      app: java-1
  template:
    metadata:
      labels:
        tier: metadata-service
        app: java-1
    spec:
      containers:
      - name: java-metadata-app
        image: savijuyal/metadata-service:v2
        ports:
          - containerPort: 8080
          # imagePullPolicy: IfNotPresent
          # readinessProbe:
          #   httpGet:
          #     path: /metadata
          #     port: 8080
